/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import principal.Pelicula;
import static principal.principal.*;

/**
 *
 * @author Mateo Beltran
 */
public class Catalogo extends javax.swing.JFrame { 
    
    Path dir = Paths.get("peliculas.txt");
    File file = new File(""+dir);
    BufferedReader fileBr;
   
    public Catalogo() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        agregar_panel();
        llenarRanking();
        actualizarRanking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obPelicula = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pRank = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 40, 0));
        setPreferredSize(new java.awt.Dimension(850, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("RANKING mas populares");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(1020, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        catalogo.setLayout(new java.awt.GridLayout(0, 5, 10, 10));
        jScrollPane1.setViewportView(catalogo);

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pRank.setLayout(new java.awt.GridLayout(0, 5, 10, 0));
        jScrollPane2.setViewportView(pRank);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Catalogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(879, 879, 879))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(739, 739, 739)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = obPelicula.getButtonCount();
        for (Enumeration e=obPelicula.getElements(); e.hasMoreElements(); )
        {
            JRadioButton b = (JRadioButton)e.nextElement();
            if (b.getModel() == obPelicula.getSelection())
            {
                Iterator it = peliculas.iterator();
                Boolean sw = false;
                while(it.hasNext() && !sw){
                    Pelicula pl = (Pelicula)it.next();
                    if(pl.getRb() == b){
                        System.out.println();
                        sw = true;
                        pla = pl.getNombre();
                        this.setVisible(false);
                        Reserva res = new Reserva();
                        res.setVisible(true);
                    }
                }
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void llenarRanking(){
        Iterator it = peliculas.iterator();
        while(it.hasNext()){
            Pelicula p = (Pelicula)it.next();
            boolean sw = false;
            Iterator ita = ranking.iterator();
            while(ita.hasNext()){
                Ranking r = (Ranking)ita.next();
                if(r.getNombre().equals(p.getNombre())){
                    sw = true;
                }
            }
            
            if(!sw){
                Ranking rk = new Ranking();
                rk.setNombre(p.getNombre());
                rk.setSrc(p.getSrc());
                rk.setCantidad(1);
                ranking.add(rk);
            } 
        }
    }
    public void actualizarRanking(){
        ordenarArray();
        
        Iterator it = ranking.iterator();
        int i = 0;
        while(it.hasNext() && i != 5){
            Ranking r = (Ranking)it.next();
            i++;
            JPanel p = new FondoPanel(r.getSrc());
            p.setVisible(true);
            p.setLayout(new GridLayout(2,1));
            
            JLabel l = new JLabel();
            l.setText(""+i);
            l.setPreferredSize(new Dimension(120,100));
            l.setFont(new Font("Sitka display",Font.BOLD, 60));
            l.setVerticalAlignment(JLabel.TOP);
            l.setForeground(Color.WHITE);
            JLabel n = new JLabel();
            n.setText(r.getNombre());
            n.setPreferredSize(new Dimension(120,30));
            n.setVerticalAlignment(JLabel.BOTTOM);
            n.setFont(new Font("Sitka display",Font.BOLD, 18));
            n.setHorizontalAlignment(JLabel.CENTER);
            n.setForeground(Color.WHITE);
            p.add(l);
            p.add(n);
            
            pRank.add(p);
           
        }
        pRank.updateUI();
    }
    public void ordenarArray(){
        Collections.sort(ranking, new Comparator<Ranking>() {
            @Override
            public int compare(Ranking o1, Ranking o2) {
                return new Integer(o2.getCantidad()).compareTo(new Integer(o1.getCantidad()));
            }
        });
    }
    public void agregar_panel(){
        try{
            if(file.exists()){
                fileBr = new BufferedReader(new FileReader(file));
                String line;
                while(( line = fileBr.readLine())!=null){
                    Pelicula pl = new Pelicula();
                    agregar_p(line,pl);
                }
                fileBr.close();
            }
        }catch(Exception e){
            e.printStackTrace();
        }     
    }
    
    public void agregar_p(String line, Pelicula pl){
        int i=0, k = 0, h = 0;
        String n ="", s="";
        while(k != 2){
            if(i == 0){
                h = i;
            }else{
                h = i+1;
            }        
            i++;
            while(!line.substring(i, i+1).equals(";"))i++;
            
            k++;  
            if(k == 1) n = line.substring(h, i);
            if(k == 2) s = line.substring(h, i);
    
        }    
        
        pl.setNombre(n);
        pl.setSrc(s);
        crear_panel(s,n,pl);
        
    }
    
    public void crear_panel(String src, String nombre , Pelicula pl){
        JPanel p = new FondoPanel(src);
        JLabel l = new JLabel();
        JRadioButton r = new JRadioButton();
        p.setLayout(new GridLayout(2,1));
        p.setSize(new Dimension(120,170));
        p.setPreferredSize(new Dimension(120,170));
        l.setText(nombre);
        l.setPreferredSize(new Dimension(90,10));
        l.setBackground(Color.RED);
        l.setVerticalAlignment(JLabel.TOP);
        l.setHorizontalAlignment(JLabel.CENTER);
        l.setFont(new Font("Sitka display",Font.BOLD, 22));
        l.setForeground(Color.GRAY);
        r.setPreferredSize(new Dimension(100,150));
        r.setHorizontalAlignment(JRadioButton.CENTER);
        r.setVerticalAlignment(JRadioButton.BOTTOM);
        obPelicula.add(r);
           
        p.add(l);
        p.add(r);
        pl.setRb(r);
        p.setVisible(true);
        
        peliculas.add(pl);
        catalogo.add(p);
        catalogo.updateUI();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel catalogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup obPelicula;
    private javax.swing.JPanel pRank;
    // End of variables declaration//GEN-END:variables
}
