/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;


import static formularios.Pagos.compra;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import principal.Pelicula;
import static principal.principal.*;

/**
 *
 * @author Yeya
 */
public class Reserva extends javax.swing.JFrame {

    Path dir = Paths.get("peliculas.txt");
    File file = new File(""+dir);
    Path dirH = Paths.get("horarios.txt");
    File fileH = new File(""+dirH);
    BufferedReader fileBr;
    int po = 0;
   
    private boolean llenado = false;
    
    
    public Reserva() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sala = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opPeliculas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        vip = new javax.swing.JRadioButton();
        tresD = new javax.swing.JRadioButton();
        dosD = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cantidad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        fechaFunciones = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        horaFunciones = new javax.swing.JComboBox<>();
        nombrePelicula = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sinopsis = new javax.swing.JTextPane();
        panelPelicula = new javax.swing.JScrollPane();
        ppp = new javax.swing.JPanel();
        cambioP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        vPelicula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vIncremento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        vTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reservar = new javax.swing.JCheckBox();
        tc = new javax.swing.JCheckBox();
        td = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel5.setText("Reservas");

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione la pelicula");

        opPeliculas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opPeliculasItemStateChanged(evt);
            }
        });
        opPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPeliculasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("Sala");

        sala.add(vip);
        vip.setText("VIP");

        sala.add(tresD);
        tresD.setText("3D");

        sala.add(dosD);
        dosD.setText("2D");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel4.setText("Cantidad de entradas");

        cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel10.setText("Fecha de funciones");

        fechaFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fechaFuncionesItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel11.setText("Hora de función");

        horaFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                horaFuncionesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(horaFunciones, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaFunciones, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(vip)
                                .addGap(18, 18, 18)
                                .addComponent(tresD)
                                .addGap(18, 18, 18)
                                .addComponent(dosD))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opPeliculas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vip)
                    .addComponent(tresD)
                    .addComponent(dosD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horaFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        nombrePelicula.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        nombrePelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePelicula.setText("Nombre pelicula");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sinopsis");

        jScrollPane2.setBackground(new java.awt.Color(153, 204, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(240, 251));

        sinopsis.setEditable(false);
        sinopsis.setBackground(new java.awt.Color(153, 204, 255));
        sinopsis.setBorder(null);
        jScrollPane2.setViewportView(sinopsis);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPelicula.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelPelicula.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ppp.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout cambioPLayout = new javax.swing.GroupLayout(cambioP);
        cambioP.setLayout(cambioPLayout);
        cambioPLayout.setHorizontalGroup(
            cambioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        cambioPLayout.setVerticalGroup(
            cambioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        ppp.add(cambioP);

        panelPelicula.setViewportView(ppp);

        jLabel7.setText("Valor Pelicula");

        vPelicula.setEditable(false);
        vPelicula.setText("0");

        jLabel8.setText("Cantidad entradas");

        vCantidad.setEditable(false);
        vCantidad.setText("0");

        jLabel9.setText("Incremento");

        vIncremento.setEditable(false);
        vIncremento.setText("0");

        jLabel12.setText("Total a pagar");

        vTotal.setEditable(false);
        vTotal.setText("0");

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("Reservar");

        reservar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                reservarStateChanged(evt);
            }
        });

        tc.setText("Tarjeta credito");
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });

        td.setText("Tarjeta Debito");

        jLabel13.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel13.setText("Metodos de pago");

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vIncremento)
                        .addComponent(vCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(vTotal)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(td)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comprar)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reservar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(vPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(vCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc)
                            .addComponent(td))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(vIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(comprar))
                    .addComponent(vTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrePelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombrePelicula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void opPeliculasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opPeliculasItemStateChanged
        // TODO add your handling code here:
       if(evt.getStateChange() ==1 && llenado){
           pla = opPeliculas.getSelectedItem().toString();
           actualizarPelicula();
           calcularTotal();
       }
        
        
    }//GEN-LAST:event_opPeliculasItemStateChanged

    private void opPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opPeliculasActionPerformed

    private void horaFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_horaFuncionesItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_horaFuncionesItemStateChanged

    private void fechaFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fechaFuncionesItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1 && llenado){
            String s = fechaFunciones.getSelectedItem().toString();
            actualizarComboBox(fileH,horaFunciones,s);
            calcularTotal();
        }
    }//GEN-LAST:event_fechaFuncionesItemStateChanged

    private void cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadStateChanged
        // TODO add your handling code here:  
        vCantidad.setText(cantidad.getValue().toString());
        calcularTotal();
    }//GEN-LAST:event_cantidadStateChanged

    private void reservarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_reservarStateChanged
        // TODO add your handling code here:
        if(reservar.isSelected()){
            vIncremento.setText("2800");
            comprar.setText("Reservar");
            
        }else{
            vIncremento.setText("0");
            comprar.setText("Comprar");
        }
        calcularTotal();
    }//GEN-LAST:event_reservarStateChanged

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        Boolean comprar = false;
        if(vip.isSelected() || tresD.isSelected() || dosD.isSelected()){
            if((int)cantidad.getValue() > 0){
              if(reservar.isSelected()){
                  comprar = true;
              }else if(tc.isSelected() || td.isSelected()){
                  comprar = true;
              }   
            }
        }
        
        if(comprar){
            CompraPeli c = new CompraPeli();
            c.setNombre(pla);
            c.setCantidad((int)cantidad.getValue());
            c.setFechaPeli(fechaFunciones.getSelectedItem().toString());
            c.setHoraPeli(horaFunciones.getSelectedItem().toString());
            c.setIncremento(Double.parseDouble(vIncremento.getText()));
            c.setTotalPagado(0);
            c.setTotalPagar(Double.parseDouble(vTotal.getText()));
            c.setValorPeli(Double.parseDouble(vPelicula.getText()));
            
            
            if(td.isSelected() && tc.isSelected()){
                c.setTipoPago(3);
            }else if(td.isSelected() && !tc.isSelected()){
                c.setTipoPago(2);
            }else if(!td.isSelected() && tc.isSelected()){
                c.setTipoPago(1);
            } 
            
            if(vip.isSelected()) c.setTipoSala("VIP");
            if(dosD.isSelected()) c.setTipoSala("2D");
            if(tresD.isSelected()) c.setTipoSala("3D");
            
            if(reservar.isSelected()){
               
               c.setTipoCompra("Reserva");
               Factura.facturar = c;
               compras.add(c);
               actualizarRanking(c);
               Factura f = new Factura();
               f.setVisible(true);
               dispose();
            }else{
                
                Pagos.compra = c;
                Pagos p = new Pagos();
               p.setVisible(true);
               dispose();
                
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Faltan datos por llenar");
        }
    }//GEN-LAST:event_comprarActionPerformed
    public void actualizarRanking(CompraPeli c){
        Iterator it = ranking.iterator();
        while(it.hasNext()){
            Ranking rk = (Ranking)it.next();
            if(rk.getNombre().equals(c.getNombre())){
                rk.setCantidad(rk.getCantidad()+c.getCantidad());
            }
        }
    }
    public void calcularTotal(){
        double valor = Double.parseDouble(vPelicula.getText());
        double cantidad = Double.parseDouble(vCantidad.getText());
        double incremento = Double.parseDouble(vIncremento.getText());
        double total = (valor * cantidad) +incremento;
        vTotal.setText(""+total);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }
    
    public void inicio(){
        agregarComboBox(file,opPeliculas, 1);
        agregarComboBox(fileH,fechaFunciones,1);
        llenado = true;
        String s = fechaFunciones.getSelectedItem().toString();
        actualizarComboBox(fileH,horaFunciones,s);
        actualizarPelicula();
        calcularTotal();
    }
    public void actualizarPelicula(){
        
        for(int i =0; i < opPeliculas.getItemCount();i++){          
            if(opPeliculas.getItemAt(i).equals(pla)){
                opPeliculas.setSelectedIndex(i);  
                try{
                    if(file.exists()){
                        fileBr = new BufferedReader(new FileReader(file));
                        String line, lineOb;
                        while(( line = fileBr.readLine())!=null){
                            lineOb = obtenerParte(line, 1);
                            if(lineOb.equals(pla)){
                                String src = obtenerParte(line,2);
                                cambioP.removeAll();
                                JPanel p = new FondoPanel(src);
                                p.setSize(new Dimension(cambioP.getWidth(),cambioP.getHeight()));
                                p.setPreferredSize(new Dimension(cambioP.getWidth(),cambioP.getHeight()));
                                p.setVisible(true);
                                cambioP.add(p);
                                panelPelicula.setBackground(Color.BLACK);
                                panelPelicula.updateUI();
                                nombrePelicula.setText(pla);
                                vPelicula.setText(obtenerParte(line,3));
                                sinopsis.setText(obtenerParte(line,4));
                            }
                            
                        }
                        fileBr.close();
                    }
                }catch(Exception e){
                    e.printStackTrace();
                } 
            }
        }
    }
    public void agregarComboBox(File file, JComboBox com, int n){
        try{
            String r ="";
            if(file.exists()){
                fileBr = new BufferedReader(new FileReader(file));
                String line, lineOb;
                while(( line = fileBr.readLine())!=null){
                    lineOb = obtenerParte(line, n);
                    if(!r.equals(lineOb)){
                        com.addItem(lineOb);
                    }
                    r = lineOb; 
                }
                fileBr.close();
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }  
    }
    
    public void actualizarComboBox(File file, JComboBox com, String r){
        try{
            
            if(file.exists()){
                com.removeAllItems();
                fileBr = new BufferedReader(new FileReader(file));
                String line, lineOb;
                while(( line = fileBr.readLine())!=null){
                    lineOb = obtenerParte(line, 1);
                    if(r.equals(lineOb)){
                        com.addItem(obtenerParte(line,2));
                    } 
                }
                fileBr.close();
                
            }
        }catch(Exception e){
            e.printStackTrace();
        } 
    }
    
    public String obtenerParte(String line, int n){
        int i=0, k = 0, h = 0;
        while(k != n){
            if(i == 0){
                h = i;
            }else{
                h = i+1;
            }        
            i++;
            while(!line.substring(i, i+1).equals(";"))i++;
            
            k++;       
        }    
        //System.out.println("IdLine: "+ line.substring(h, i));
        return line.substring(h,i);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cambioP;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JButton comprar;
    private javax.swing.JRadioButton dosD;
    private javax.swing.JComboBox<String> fechaFunciones;
    private javax.swing.JComboBox<String> horaFunciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombrePelicula;
    private javax.swing.JComboBox<String> opPeliculas;
    private javax.swing.JScrollPane panelPelicula;
    private javax.swing.JPanel ppp;
    private javax.swing.JCheckBox reservar;
    private javax.swing.ButtonGroup sala;
    private javax.swing.JTextPane sinopsis;
    private javax.swing.JCheckBox tc;
    private javax.swing.JCheckBox td;
    private javax.swing.JRadioButton tresD;
    private javax.swing.JTextField vCantidad;
    private javax.swing.JTextField vIncremento;
    private javax.swing.JTextField vPelicula;
    private javax.swing.JTextField vTotal;
    private javax.swing.JRadioButton vip;
    // End of variables declaration//GEN-END:variables
}
